pipeline {
    agent {
        docker {
            image 'node:20.16.0'
            args '-u root:root -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -v /usr/local/bin/docker:/usr/local/bin/docker'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh 'node -v && npm -v'
            }
        }
       
        stage('Install') {
            steps {
                sh 'cd frontend && npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm build'
            }
        }
    }
}
