pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Setup') {
            steps {
                script {
                    def nodeVersion = '20.19.0'
                    def npmVersion = '10.8.2'
                    def nvmDir = "${env.WORKSPACE}/.nvm"

                    sh """
                        mkdir -p ${nvmDir}
                        export NVM_DIR=${nvmDir}
                        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
                        source ${nvmDir}/nvm.sh
                        nvm install ${nodeVersion}
                        nvm use ${nodeVersion}
                        nvm alias default ${nodeVersion}
                        npm install -g npm@${npmVersion}
                    """
                }
            }
        }
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm Build'
            }
        }
    }
}
