pipeline {
    agent {
        docker {
            image 'node:20'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh 'node -v && npm -v'
            }
        }
       
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm Build'
            }
        }
    }
}
