name: Build and Push Backend Docker Image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-push-backend-to-docker:
    runs-on: ubuntu-latest

    steps:
      #Step 1 Checkout Code in repo
      - name: Checkout repository
        uses: actions/checkout@v4

      #Step 2: Debug Docker environment
      - name: Debug Docker environment
        run: |
          docker version
          docker info

      #Step 3 Login to DockerHub (if Image is private)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #Step 4 Build Docker Image
      - name: Build Docker image for TestPrep Backend
        run: |
          docker build --build-arg GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} --build-arg MONGO_URI="${{ secrets.MONGO_URI }}" -t ${{ secrets.DOCKERHUB_USERNAME }}/testprep_b:latest -f backend/Dockerfile backend/ 
      
      #Step 5 Push Build Image to docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/testprep_b:latest


  deploy:
    needs: build-and-push-backend-to-docker
    runs-on: self-hosted
    steps:
      #Step 1 Pull Docker Image 
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testprep_b:latest

      #Step 2 Remove existing running containers (if running)
      - name: Stop and remove existing container (if running)
        run: |
          docker stop testprep_backend || true
          docker rm testprep_backend || true

      #Step 3 Run Docker container
      - name: Run Docker container
        run: |
          docker run -d --name testprep_backend -p 3001:3001 ${{ secrets.DOCKERHUB_USERNAME }}/testprep_b:latest
